name: Publish WeChat Miniprogram

description: Publish your WeChat miniprogram to Wechat Platform

branding:
  icon: upload
  color: green

inputs:
  upload-key:
    description: A private key used to authenticate and upload your miniprogram project.
  project-path:
    description: >
      The root directory of WeChat miniprogram.
      Default: '.'
  version:
    description: >
      Release version.
      If it is empty and package.json exists, the version in package.json will be used.

runs:
  using: node12
  pre: build.js
  main: dist/index.js
